name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: seaquail
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start mysql server
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE seaquail; -uroot -proot'
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          MAX_RETRIES=20
          RETRY_INTERVAL=5
          TRIES=0
          until mysqladmin ping -hmysql --silent; do
            if [ "$TRIES" -ge "$MAX_RETRIES" ]; then
              echo "MySQL did not become ready in time."
              exit 1
            fi
            echo "Waiting for MySQL..."
            sleep $RETRY_INTERVAL
            TRIES=$((TRIES+1))
          done

      - name: Run update_db.py
        env:
          MYSQL_HOST: mysql
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: seaquail
        run: python3 dbSetup/update_db.py

      - name: Print MySQL logs on failure
        if: failure()
        run: docker logs $(docker ps -q -f ancestor=mysql:8) || echo "No MySQL container logs found."
