name: Update Database

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: seaquail
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysql -uroot -ppassword -e 'SELECT 1'"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=10
          --cpus="1.5"
          --memory="512m"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          MAX_RETRIES=20
          RETRY_INTERVAL=5
          TRIES=0
          until mysql -uroot -ppassword -hmysql -e 'SELECT 1' &> /dev/null; do
            if [ "$TRIES" -ge "$MAX_RETRIES" ]; then
              echo "MySQL did not become ready in time."
              exit 1
            fi
            echo "Waiting for MySQL..."
            sleep $RETRY_INTERVAL
            TRIES=$((TRIES+1))
          done

      - name: Run update_db.py
        env:
          MYSQL_HOST: mysql
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: seaquail
        run: python3 dbSetup/update_db.py

      - name: Print MySQL logs on failure
        if: failure()
        run: docker logs $(docker ps -q -f ancestor=mysql:8) || echo "No MySQL container logs found."
